In [1]:
import numpy as np

In [46]:
defaultzschedule = np.asarray([
    [1, 2, 3, 4, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 2, 3, 4],
    [2, 3, 0, 0, 4, 1, 0, 0],
    [3, 0, 4, 0, 2, 0, 1, 0]
])
defaultxschedule = np.asarray([
    [1, 2, 3, 4, 5, 6, 7, 8]
])

def checkvalidschedule(schedule):
    for row in schedule:
        seen = set()
        for val in row:
            if val != 0:
                if val in seen:
                    return False
                seen.add(val)
    for col_idx in range(schedule.shape[1]):
        seen = set()
        for row_idx in range(schedule.shape[0]):
            val = schedule[row_idx][col_idx]
            if val != 0:
                if val in seen:
                    return False
                seen.add(val)
    return True

def randomize_schedule(schedule, max_attempts=1000):
    if max_attempts == 0:
        return None
    for i in range(len(schedule)):
        nonzeros = list(range(1, max(schedule[i]) + 1))
        np.random.shuffle(nonzeros)
        for j in range(len(schedule[i])):
            if schedule[i][j] != 0:
                schedule[i][j] = nonzeros.pop()
    if checkvalidschedule(schedule):
        return schedule, max_attempts
    else:
        return randomize_schedule(schedule, max_attempts - 1)


In [82]:
newzschedule, n = randomize_schedule(defaultzschedule, 1000)
print(1000 - n)
print(newzschedule)
newxschedule, n = randomize_schedule(defaultxschedule, 1000)
print(1000 - n)
print(newxschedule)


1
[[1 3 2 4 0 0 0 0]
 [0 0 0 0 4 3 2 1]
 [2 1 0 0 3 4 0 0]
 [3 0 1 0 2 0 4 0]]
0
[[5 2 4 7 3 1 6 8]]


In [23]:
arr = [1, 2, 3, 4, 0 ,0 , 0, 0]
nonzeros = list(range(1, max(arr) + 1))
print(nonzeros)
np.random.shuffle(nonzeros)
for i in range(len(arr)):
    if arr[i] != 0:
        arr[i] = nonzeros.pop()
print(arr)

[1, 2, 3, 4]
[2, 3, 4, 1, 0, 0, 0, 0]
